[FOLDERS]
raw_texts_folder_name = 'raw'
translation_folder_name = 'translation'
result_folder_name = 'result'
patch_folder_name = 'patch'
source_folder_name = 'source'
temp_folder_name = 'temp'

[FILES]
export_json_file = 'export.json'
result_file_name = 'Sqex03DataMessage.txt'

[TRANSLATION.FILES]
to_not_translate = []
to_translate = []

[TRANSLATION.PATHS]
to_translate = [
    'translation'
]
