[TYPER.MAKE_TRANSLATION_FOLDER]
help = 'Pega os textos e agrupa em arquivos .CSV amigáveis para tradução e revisão.'

[TYPER.MAKE_RESULT_FOLDER]
help = 'Pega os arquivos .CSV de tradução e retorna no formato raw (.txt).'

[TYPER.BUILDER]
help = 'Módulo com capacidades de organizar e traduzir os textos, usando alguma ferramenta de tradução.'

[TYPER.TRANSLATE]
help = 'Comando que traduz de forma automática os arquivos de textos.'

[TYPER.UPDATE_XXX]
help = 'Atualiza os arquivos .XXX usando hexadecimal para aplicar tradução em textos que não foram possíveis serem traduzidos.'
